apiVersion : apps/v1
kind: Deployment
metadata:
  name: sammadupipelinesjavascriptdocker 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sammadupipelinesjavascriptdocker 
    spec:
      containers:
        - name: sammadupipelinesjavascriptdocker 
          image: samsacr.azurecr.io/sammadupipelinesjavascriptdocker
          ports:
          - containerPort: 8080
